#!/bin/bash
cd /home/ubuntu/javaapp
sudo apt-get install -y java-1.8.0-openjdk-devel
sudo apt-get install -y tar
sudo apt-get install -y wget
wget https://s3.amazonaws.com/dhqs-mirror-iad/apache-tomcat-8.0.39.tar.gz
mkdir /opt/tomcat
tar xvf apache-tomcat-8*tar.gz -C /opt/tomcat --strip-components=1
cd /opt/tomcat
sed -i 's|port="8080"|port="80"|g' /opt/tomcat/conf/server.xml
ls -ltrh /home/ubuntu/javaapp/
ls -ltrh /opt/tomcat/
mv /home/ubuntu/javaapp/Helloworld.war /opt/tomcat/webapps/
